ktor:
    application:
        modules:
            - com.es.ApplicationKt.module
    deployment:
        port: 8081
        host: "127.0.0.1"
    externalApi:
        bggUrl: "https://boardgamegeek.com/xmlapi2/"
